=== gonicus/clacks/agent/src/clacks/agent/data/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.gonicus.de/Objects" 
  elementFormDefault="qualified" 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:o="http://www.gonicus.de/Objects">

  <complexType name="Object">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="DisplayName" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Templates" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Template" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="Dialogs" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Dialog" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BackendParameters" type="o:BackendParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Attributes" type="o:Attributes" maxOccurs="1" minOccurs="0"></element>
      <element name="Container" type="o:ContainerType" maxOccurs="1" minOccurs="0"></element>
      <element name="Extends" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BaseObject" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Methods" type="o:Methods" maxOccurs="1" minOccurs="0"></element>
      <element name="Hooks" type="o:Hooks" maxOccurs="1" minOccurs="0"></element>
      <element name="FixedRDN" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="StructuralInvisible" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="RequiresExtension" type="o:RequiresExtension" maxOccurs="1" minOccurs="0"></element>
      <element name="Find" type="o:Find" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Attributes">
    <choice maxOccurs="unbounded">
      <element name="ForeignAttribute" type="o:ForeignAttribute" />
      <element name="Attribute" type="o:Attribute" />
    </choice>
  </complexType>

  <complexType name="ForeignAttribute" >
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="Attribute">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="0">
      </element>
      <element name="DependsOn" type="o:DependsOn" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Values" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
              <element name="Value" maxOccurs="unbounded" minOccurs="0" type="o:ValueWithKey"></element>
          </sequence>
          <attribute name="populate" type="string" use="optional"/>
        </complexType>
      </element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="BackendType" type="o:AttributeBackendTypes" maxOccurs="1" minOccurs="0"></element>
      <element name="Validators" type="o:Validator" maxOccurs="1" minOccurs="0"></element>
      <element name="InFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="OutFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="MultiValue" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="ReadOnly" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Mandatory" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Unique" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="BlockedBy" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Attribute" maxOccurs="unbounded" minOccurs="1">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="value" type="string"></attribute>
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="CaseSensitive" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="References" type="o:References" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <simpleType name="AttributeTypes">
    <restriction base="string"></restriction>
  </simpleType>

  <simpleType name="AttributeBackendTypes">
    <restriction base="string">
      <enumeration value="Boolean"></enumeration>
      <enumeration value="String"></enumeration>
      <enumeration value="UnicodeString"></enumeration>
      <enumeration value="Integer"></enumeration>
      <enumeration value="Timestamp"></enumeration>
      <enumeration value="Date"></enumeration>
      <enumeration value="Binary"></enumeration>
    </restriction>
  </simpleType>

  <complexType name="ContainerType">
    <sequence>
      <element name="Type" type="token" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <element name="Objects" type="o:Objects"></element>

  <complexType name="Objects">
    <sequence>
      <element name="Object" type="o:Object" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Methods">
    <sequence>
      <element name="Method" type="o:Method" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Hooks">
    <sequence>
      <element name="Hook" type="o:Hook" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Method">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="MethodParameters" type="o:MethodParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Hook">
    <all>
      <element name="Type" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="PreCreate"></enumeration>
            <enumeration value="PreUpdate"></enumeration>
            <enumeration value="PreRemove"></enumeration>
            <enumeration value="PostCreate"></enumeration>
            <enumeration value="PostUpdate"></enumeration>
            <enumeration value="PostRemove"></enumeration>
          </restriction>
        </simpleType>
      </element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Parameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="FilterChain">
    <choice>
      <element name="FilterEntry" type="o:FilterEntry" maxOccurs="unbounded" minOccurs="1"></element>
    </choice>
  </complexType>

  <complexType name="Choice">
    <sequence>
      <element name="When" type="o:When" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="When">
    <sequence>
      <element name="ConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Else" type="o:Else" maxOccurs="1" minOccurs="0"></element>
    </sequence>

  </complexType>

  <complexType name="ValueWithKey">
    <simpleContent>
      <extension base="string">
        <attribute name="key" type="string"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="FilterElement">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Filter">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Else">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="ConditionChain">
    <choice>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="Condition">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Validator">
    <choice>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="FilterEntry">
    <choice>
      <element name="Filter" type="o:Filter" maxOccurs="1" minOccurs="0"></element>
      <element name="Choice" type="o:Choice" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="ConditionOperator">
    <sequence>
      <element name="Operator" type="o:NewType" maxOccurs="1" minOccurs="1"></element>
      <element name="LeftConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="RightConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="DependsOn">
    <sequence>
      <element name="Attribute" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="RequiresExtension">
    <sequence>
      <element name="Extension" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Find">
    <sequence>
      <element name="Aspect" type="o:Aspect" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Result">
    <sequence>
      <element name="Map" type="o:Map" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Map">
    <sequence>
      <element name="Source" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Destination" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Aspect">
    <sequence>
      <element name="Tag" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="Keyword" type="string" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Search" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Resolve" type="o:Resolve" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Result" type="o:Result" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

    <complexType name="Resolve">
    <simpleContent>
      <extension base="string">
        <attribute name="filter" type="string"/>
        <attribute name="type" type="string" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="NewType">
    <restriction base="token">
      <enumeration value="or"></enumeration>
      <enumeration value="and"></enumeration>
    </restriction>
  </simpleType>


  <complexType name="Parameters">
    <sequence>
      <element name="Parameter" type="o:Parameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="CommandParameter">
    <sequence>
      <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>


  <complexType name="MethodParameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="MethodParameters">
    <sequence>
      <element name="MethodParameter" type="o:MethodParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="BackendParameter">
    <simpleContent>
      <extension base="string">
        <anyAttribute processContents="lax" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="BackendParameters">
    <sequence>
      <element name="Backend" type="o:BackendParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="References">
    <sequence>
      <element name="Reference" type="o:Reference" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Reference">
    <sequence>
      <element name="Object" type="token"></element>
      <element name="Attribute" type="token"></element>
    </sequence>
  </complexType>
</schema>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/gofon-hardware.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>goFonHardware</Name>
    <DisplayName>goFonHardware</DisplayName>
    <Description>defines a telephone (v2.7)</Description>
    <Backend>LDAP</Backend>
    <BackendParameters>
      <Backend objectClasses="goFonHardware" RDN="cn">LDAP</Backend>
    </BackendParameters>
    <Attributes>
      <Attribute>
        <Name>macAddress</Name>
        <Description>MAC address</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>true</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>ipHostNumber</Name>
        <Description>IP address</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>true</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>cn</Name>
        <Description>RFC4519: common name(s) for which the entity is known by</Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>goFonAuth</Name>
        <Description>sets the sip.conf auth parameter</Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>goFonQualify</Name>
        <Description>sets the sip.conf qualify parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonMSN</Name>
        <Description>sets the sip.conf msn parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^\+[0-9]{2}\s*[0-9\s]+$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>description</Name>
        <Description>RFC4519: descriptive information</Description>
        <Type>UnicodeString</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>goFonSecret</Name>
        <Description>sets the sip.conf secret parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonType</Name>
        <Description>sets the sip.conf type parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
        <Default>friend</Default>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonAccountCode</Name>
        <Description>sets the sip.conf accountcode parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonDmtfMode</Name>
        <Description>sets the sip.conf dmtfmode parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonOutkey</Name>
        <Description>sets the sip.conf outkey parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonDefaultIP</Name>
        <Description>sets the sip.conf defaultip parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
        <Default>dynamic</Default>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonHost</Name>
        <Description>sets the sip.conf host parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonInkeys</Name>
        <Description>sets the sip.conf inkeys parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonTrunk</Name>
        <Description>sets the sip.conf trunk parameter</Description>
        <Type>String</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonDeny</Name>
        <Description>sets the sip.conf deny parameter</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>goFonPermit</Name>
        <Description>sets the sip.conf permit parameter</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>RegEx</Name>
            <Param>^[\x00-\x7F]*$</Param>
          </Condition>
        </Validators>
      </Attribute>
    </Attributes>
    <BaseObject>true</BaseObject>
  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/ou.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>OrganizationalUnit</Name>
    <DisplayName>Organizational unit</DisplayName>
    <Description>Organizational unit</Description>
    <BackendParameters>
      <Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>
    <Attributes>
      <Attribute>
        <Name>ou</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>description</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>businessCategory</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>st</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>l</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>postalAddress</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>telephoneNumber</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>facsimileTelephoneNumber</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>manager</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
        <Validators>
          <Condition>
            <Name>ObjectWithPropertyExists</Name>
            <Param>User</Param>
            <Param>dn</Param>
          </Condition>
        </Validators>
      </Attribute>
    </Attributes>
    <Container>
      <Type>PeopleContainer</Type>
      <Type>GroupContainer</Type>
      <Type>OrganizationalUnit</Type>
      <Type>Organization</Type>
      <Type>Locality</Type>
      <Type>DomainComponent</Type>
      <Type>Domain</Type>
      <Type>Country</Type>
      <Type>SambaDomain</Type>
      <Type>AclRole</Type>
    </Container>
    <BaseObject>true</BaseObject>
    <Find>
      <Aspect>
        <Tag>OrganizationalUnit</Tag>
        <Keyword>Unit</Keyword>
        <Keyword>Organization</Keyword>
        <Search>ou</Search>
        <Resolve filter="DN">manager</Resolve>
        <Result>
          <Map>
            <Source>ou</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>
  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/trustaccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>TrustAccount</Name>
    <Description>A trust account extension</Description>
    <DisplayName>Trust account</DisplayName>
    <BaseObject>false</BaseObject>
    <BackendParameters>
      <Backend objectClasses="trustAccount">LDAP</Backend>
      <Backend accessTo="Device:cn,">ObjectHandler</Backend>
    </BackendParameters>
    <Templates>
      <Template>trustaccount.ui</Template>
    </Templates>
    <Backend>LDAP</Backend>
    <Attributes>
      <Attribute>
        <Name>trustModel</Name>
        <Description>Access scheme</Description>
        <Type>String</Type>
        <Values>
          <Value key="">Disabled</Value>
          <Value key="fullaccess">Full access</Value>
          <Value key="byhost">By host</Value>
        </Values>
        <Default></Default>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>accessTo</Name>
        <Description>Access to which servers user is allowed</Description>
        <Backend>LDAP</Backend>
        <Type>String</Type>
        <ReadOnly>false</ReadOnly>
        <MultiValue>true</MultiValue>
        <BlockedBy>
          <Attribute value="">trustModel</Attribute>
          <Attribute value="fullaccess">trustModel</Attribute>
        </BlockedBy>
      </Attribute>
    </Attributes>
    <Extends>
      <Value>PosixGroup</Value>
      <Value>User</Value>
    </Extends>
  </Object>
</Objects>
