=== gonicus/clacks/agent/src/clacks/agent/data/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.gonicus.de/Objects" 
  elementFormDefault="qualified" 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:o="http://www.gonicus.de/Objects">

  <complexType name="Object">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="DisplayName" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Templates" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Template" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="Dialogs" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Dialog" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BackendParameters" type="o:BackendParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Attributes" type="o:Attributes" maxOccurs="1" minOccurs="0"></element>
      <element name="Container" type="o:ContainerType" maxOccurs="1" minOccurs="0"></element>
      <element name="Extends" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BaseObject" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Methods" type="o:Methods" maxOccurs="1" minOccurs="0"></element>
      <element name="Hooks" type="o:Hooks" maxOccurs="1" minOccurs="0"></element>
      <element name="FixedRDN" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="StructuralInvisible" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="RequiresExtension" type="o:RequiresExtension" maxOccurs="1" minOccurs="0"></element>
      <element name="Find" type="o:Find" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Attributes">
    <choice maxOccurs="unbounded">
      <element name="ForeignAttribute" type="o:ForeignAttribute" />
      <element name="Attribute" type="o:Attribute" />
    </choice>
  </complexType>

  <complexType name="ForeignAttribute" >
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="Attribute">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="0">
      </element>
      <element name="DependsOn" type="o:DependsOn" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Values" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
              <element name="Value" maxOccurs="unbounded" minOccurs="0" type="o:ValueWithKey"></element>
          </sequence>
          <attribute name="populate" type="string" use="optional"/>
        </complexType>
      </element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="BackendType" type="o:AttributeBackendTypes" maxOccurs="1" minOccurs="0"></element>
      <element name="Validators" type="o:Validator" maxOccurs="1" minOccurs="0"></element>
      <element name="InFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="OutFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="MultiValue" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="ReadOnly" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Mandatory" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Unique" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="BlockedBy" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Attribute" maxOccurs="unbounded" minOccurs="1">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="value" type="string"></attribute>
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="CaseSensitive" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="References" type="o:References" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <simpleType name="AttributeTypes">
    <restriction base="string"></restriction>
  </simpleType>

  <simpleType name="AttributeBackendTypes">
    <restriction base="string">
      <enumeration value="Boolean"></enumeration>
      <enumeration value="String"></enumeration>
      <enumeration value="UnicodeString"></enumeration>
      <enumeration value="Integer"></enumeration>
      <enumeration value="Timestamp"></enumeration>
      <enumeration value="Date"></enumeration>
      <enumeration value="Binary"></enumeration>
    </restriction>
  </simpleType>

  <complexType name="ContainerType">
    <sequence>
      <element name="Type" type="token" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <element name="Objects" type="o:Objects"></element>

  <complexType name="Objects">
    <sequence>
      <element name="Object" type="o:Object" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Methods">
    <sequence>
      <element name="Method" type="o:Method" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Hooks">
    <sequence>
      <element name="Hook" type="o:Hook" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Method">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="MethodParameters" type="o:MethodParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Hook">
    <all>
      <element name="Type" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="PreCreate"></enumeration>
            <enumeration value="PreUpdate"></enumeration>
            <enumeration value="PreRemove"></enumeration>
            <enumeration value="PostCreate"></enumeration>
            <enumeration value="PostUpdate"></enumeration>
            <enumeration value="PostRemove"></enumeration>
          </restriction>
        </simpleType>
      </element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Parameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="FilterChain">
    <choice>
      <element name="FilterEntry" type="o:FilterEntry" maxOccurs="unbounded" minOccurs="1"></element>
    </choice>
  </complexType>

  <complexType name="Choice">
    <sequence>
      <element name="When" type="o:When" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="When">
    <sequence>
      <element name="ConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Else" type="o:Else" maxOccurs="1" minOccurs="0"></element>
    </sequence>

  </complexType>

  <complexType name="ValueWithKey">
    <simpleContent>
      <extension base="string">
        <attribute name="key" type="string"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="FilterElement">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Filter">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Else">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="ConditionChain">
    <choice>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="Condition">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Validator">
    <choice>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="FilterEntry">
    <choice>
      <element name="Filter" type="o:Filter" maxOccurs="1" minOccurs="0"></element>
      <element name="Choice" type="o:Choice" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="ConditionOperator">
    <sequence>
      <element name="Operator" type="o:NewType" maxOccurs="1" minOccurs="1"></element>
      <element name="LeftConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="RightConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="DependsOn">
    <sequence>
      <element name="Attribute" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="RequiresExtension">
    <sequence>
      <element name="Extension" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Find">
    <sequence>
      <element name="Aspect" type="o:Aspect" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Result">
    <sequence>
      <element name="Map" type="o:Map" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Map">
    <sequence>
      <element name="Source" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Destination" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Aspect">
    <sequence>
      <element name="Tag" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="Keyword" type="string" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Search" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Resolve" type="o:Resolve" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Result" type="o:Result" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

    <complexType name="Resolve">
    <simpleContent>
      <extension base="string">
        <attribute name="filter" type="string"/>
        <attribute name="type" type="string" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="NewType">
    <restriction base="token">
      <enumeration value="or"></enumeration>
      <enumeration value="and"></enumeration>
    </restriction>
  </simpleType>


  <complexType name="Parameters">
    <sequence>
      <element name="Parameter" type="o:Parameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="CommandParameter">
    <sequence>
      <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>


  <complexType name="MethodParameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="MethodParameters">
    <sequence>
      <element name="MethodParameter" type="o:MethodParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="BackendParameter">
    <simpleContent>
      <extension base="string">
        <anyAttribute processContents="lax" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="BackendParameters">
    <sequence>
      <element name="Backend" type="o:BackendParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="References">
    <sequence>
      <element name="Reference" type="o:Reference" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Reference">
    <sequence>
      <element name="Object" type="token"></element>
      <element name="Attribute" type="token"></element>
    </sequence>
  </complexType>
</schema>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/group-samba.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>SambaGroup</Name>
    <Description>A samba extension for a posix group</Description>
    <DisplayName>Samba group extension</DisplayName>
    <Templates>
      <Template>group-samba.ui</Template>
    </Templates>
    <BackendParameters>
      <Backend objectClasses="sambaGroupMapping">LDAP</Backend>
      <Backend sambaSIDList="SambaGroup:sambaSID,">ObjectHandler</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>

    <Attributes>
      <Attribute>
        <Name>sambaSID</Name>
        <Description>Security ID</Description>
        <Type>String</Type>
        <DependsOn>
          <Attribute>sambaDomainName</Attribute>
          <Attribute>sambaGroupType</Attribute>
        </DependsOn>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>GenerateSambaSid</Name>
                <Param>group</Param>
                <Param>%(gidNumber)s</Param>
                <Param>%(sambaDomainName)s</Param>
                <Param>%(sambaGroupType)s</Param>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
        <ReadOnly>true</ReadOnly>
      </Attribute>
      <Attribute>
        <Name>sambaDomainName</Name>
        <Description></Description>
        <Backend>NULL</Backend>
        <Type>String</Type>
        <Mandatory>true</Mandatory>
	      <Values populate="getSambaDomainNames" />
				<InFilter>
					<FilterChain>
						<FilterEntry>
							<Filter>
                <Name>DetectSambaDomainFromSID</Name>
                <Param>%(sambaSID)s</Param>
							</Filter>
						</FilterEntry>
					</FilterChain>
				</InFilter>
      </Attribute>
      <ForeignAttribute>
        <Name>gidNumber</Name>
      </ForeignAttribute>
      <Attribute>
        <Name>sambaGroupType</Name>
        <Description>Samba group(0) Domain administrators(512) Domain users(513) Domain guests(514)</Description>
        <Type>Integer</Type>
        <Values>
          <Value key="0">Samba group</Value>
          <Value key="512">Domain administrators</Value>
          <Value key="513">Domain users</Value>
          <Value key="514">Domain guests</Value>
        </Values>
        <Default>0</Default>
        <ReadOnly>false</ReadOnly>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>displayName</Name>
        <Description>Displayed name</Description>
        <Type>UnicodeString</Type>
      </Attribute>
      <Attribute>
        <Name>sambaSIDList</Name>
        <Description>A list of member-SIDs</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
        <References>
          <Reference>
            <Object>SambaGroup</Object>
            <Attribute>sambaSID</Attribute>
          </Reference>
        </References>
        <Validators>
          <ConditionOperator>
            <Operator>and</Operator>
            <LeftConditionChain>
              <Condition>
                <Name>CheckSambaSIDList</Name>
              </Condition>
            </LeftConditionChain>
            <RightConditionChain>
              <Condition>
                <Name>ObjectWithPropertyExists</Name>
                <Param>SambaGroup</Param>
                <Param>sambaSID</Param>
              </Condition>
            </RightConditionChain>
          </ConditionOperator>
        </Validators>
      </Attribute>
    </Attributes>
    <Extends>
      <Value>PosixGroup</Value>
    </Extends>
    <BaseObject>false</BaseObject>
  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/group-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>GroupContainer</Name>
		<DisplayName>Groups</DisplayName>
		<Description>Organizational unit that can contain groups</Description>
		<BackendParameters>
			<Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>

		<BaseObject>true</BaseObject>
		<FixedRDN>ou=groups</FixedRDN>
		<Container>
			<Type>PosixGroup</Type>
			<Type>GroupOfNames</Type>
		</Container>
    <Find>
      <Aspect>
        <Tag>GroupContainer</Tag>
        <Keyword>Groups</Keyword>
        <Search>ou</Search>
        <Resolve filter="DN">manager</Resolve>
        <Result>
          <Map>
            <Source>ou</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>
	</Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/people-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>PeopleContainer</Name>
		<DisplayName>Users</DisplayName>
		<Description>Organizational unit that can contain users</Description>
		<BackendParameters>
			<Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>
		<Container>
			<Type>User</Type>
		</Container>
		<BaseObject>true</BaseObject>
		<FixedRDN>ou=people</FixedRDN>
    <Find>
      <Aspect>
        <Tag>PeopleContainer</Tag>
        <Keyword>User</Keyword>
        <Search>ou</Search>
        <Resolve filter="DN">manager</Resolve>
        <Result>
          <Map>
            <Source>ou</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>
	</Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/group-posix.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>PosixGroup</Name>
    <Description>A posix group</Description>
    <Templates>
      <Template>group-posix.ui</Template>
    </Templates>
    <DisplayName>Posix group</DisplayName>
    <BackendParameters>
      <Backend objectClasses="posixGroup"
        RDN="cn">LDAP</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>

    <Attributes>
      <Attribute>
        <Name>cn</Name>
        <Description>Common Name</Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>description</Name>
        <Description>Description</Description>
        <Type>UnicodeString</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>false</Mandatory>
      </Attribute>
      <Attribute>
        <Name>gidNumber</Name>
        <Description>The primary group number  number</Description>
        <Type>Integer</Type>
        <MultiValue>false</MultiValue>
        <Mandatory>true</Mandatory>
        <Default>-1</Default>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>GetNextID</Name>
                <Param>gidNumber</Param>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
        <Validators>
          <Condition>
            <Name>Smaller</Name>
            <Param>65500</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>memberUid</Name>
        <Description>A list of member-uids</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
        <References>
          <Reference>
            <Object>PosixUser</Object>
            <Attribute>uid</Attribute>
          </Reference>
        </References>
      </Attribute>
    </Attributes>
    <BaseObject>true</BaseObject>

    <Find>
	<Aspect>
		<Tag>PosixGroup</Tag>
		<Keyword>Group</Keyword>
		<Keyword>Member</Keyword>
		<Keyword>Membership</Keyword>
		<Search>cn</Search>
		<Search>description</Search>
		<Resolve type="User" filter="uid">memberUid</Resolve>
		<Result>
			<Map>
				<Source>cn</Source>
				<Destination>title</Destination>
			</Map>
		</Result>
	</Aspect>
</Find>

  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/group-asterisk.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
    <Object>
        <Name>AsteriskGroup</Name>
        <Description>An asterisl extension for a group</Description>
        <DisplayName>Asterisk group extension</DisplayName>
        <BackendParameters>
            <Backend objectClasses="goFonPickupGroup">LDAP</Backend>
        </BackendParameters>
        <Backend>LDAP</Backend>
        <Extends>
            <Value>PosixGroup</Value>
        </Extends>
        <BaseObject>false</BaseObject>
    </Object>
</Objects>
