=== gonicus/clacks/agent/src/clacks/agent/data/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.gonicus.de/Objects" 
  elementFormDefault="qualified" 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:o="http://www.gonicus.de/Objects">

  <complexType name="Object">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="DisplayName" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Templates" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Template" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="Dialogs" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Dialog" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BackendParameters" type="o:BackendParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Attributes" type="o:Attributes" maxOccurs="1" minOccurs="0"></element>
      <element name="Container" type="o:ContainerType" maxOccurs="1" minOccurs="0"></element>
      <element name="Extends" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
          </sequence>
        </complexType>
      </element>
      <element name="BaseObject" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Methods" type="o:Methods" maxOccurs="1" minOccurs="0"></element>
      <element name="Hooks" type="o:Hooks" maxOccurs="1" minOccurs="0"></element>
      <element name="FixedRDN" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="StructuralInvisible" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="RequiresExtension" type="o:RequiresExtension" maxOccurs="1" minOccurs="0"></element>
      <element name="Find" type="o:Find" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Attributes">
    <choice maxOccurs="unbounded">
      <element name="ForeignAttribute" type="o:ForeignAttribute" />
      <element name="Attribute" type="o:Attribute" />
    </choice>
  </complexType>

  <complexType name="ForeignAttribute" >
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="Attribute">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Description" type="string" maxOccurs="1" minOccurs="0">
      </element>
      <element name="DependsOn" type="o:DependsOn" maxOccurs="1" minOccurs="0"></element>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Values" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
              <element name="Value" maxOccurs="unbounded" minOccurs="0" type="o:ValueWithKey"></element>
          </sequence>
          <attribute name="populate" type="string" use="optional"/>
        </complexType>
      </element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="BackendType" type="o:AttributeBackendTypes" maxOccurs="1" minOccurs="0"></element>
      <element name="Validators" type="o:Validator" maxOccurs="1" minOccurs="0"></element>
      <element name="InFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="OutFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"></element>
      <element name="MultiValue" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="ReadOnly" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Mandatory" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Unique" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="BlockedBy" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Attribute" maxOccurs="unbounded" minOccurs="1">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="value" type="string"></attribute>
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="CaseSensitive" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="References" type="o:References" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <simpleType name="AttributeTypes">
    <restriction base="string"></restriction>
  </simpleType>

  <simpleType name="AttributeBackendTypes">
    <restriction base="string">
      <enumeration value="Boolean"></enumeration>
      <enumeration value="String"></enumeration>
      <enumeration value="UnicodeString"></enumeration>
      <enumeration value="Integer"></enumeration>
      <enumeration value="Timestamp"></enumeration>
      <enumeration value="Date"></enumeration>
      <enumeration value="Binary"></enumeration>
    </restriction>
  </simpleType>

  <complexType name="ContainerType">
    <sequence>
      <element name="Type" type="token" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <element name="Objects" type="o:Objects"></element>

  <complexType name="Objects">
    <sequence>
      <element name="Object" type="o:Object" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Methods">
    <sequence>
      <element name="Method" type="o:Method" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Hooks">
    <sequence>
      <element name="Hook" type="o:Hook" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Method">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="MethodParameters" type="o:MethodParameters" maxOccurs="1" minOccurs="0"></element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Hook">
    <all>
      <element name="Type" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="PreCreate"></enumeration>
            <enumeration value="PreUpdate"></enumeration>
            <enumeration value="PreRemove"></enumeration>
            <enumeration value="PostCreate"></enumeration>
            <enumeration value="PostUpdate"></enumeration>
            <enumeration value="PostRemove"></enumeration>
          </restriction>
        </simpleType>
      </element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="Parameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
    </all>
  </complexType>

  <complexType name="FilterChain">
    <choice>
      <element name="FilterEntry" type="o:FilterEntry" maxOccurs="unbounded" minOccurs="1"></element>
    </choice>
  </complexType>

  <complexType name="Choice">
    <sequence>
      <element name="When" type="o:When" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="When">
    <sequence>
      <element name="ConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Else" type="o:Else" maxOccurs="1" minOccurs="0"></element>
    </sequence>

  </complexType>

  <complexType name="ValueWithKey">
    <simpleContent>
      <extension base="string">
        <attribute name="key" type="string"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="FilterElement">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Filter">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Else">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="ConditionChain">
    <choice>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="Condition">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Validator">
    <choice>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"></element>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="FilterEntry">
    <choice>
      <element name="Filter" type="o:Filter" maxOccurs="1" minOccurs="0"></element>
      <element name="Choice" type="o:Choice" maxOccurs="1" minOccurs="0"></element>
    </choice>
  </complexType>

  <complexType name="ConditionOperator">
    <sequence>
      <element name="Operator" type="o:NewType" maxOccurs="1" minOccurs="1"></element>
      <element name="LeftConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
      <element name="RightConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="DependsOn">
    <sequence>
      <element name="Attribute" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="RequiresExtension">
    <sequence>
      <element name="Extension" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Find">
    <sequence>
      <element name="Aspect" type="o:Aspect" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Result">
    <sequence>
      <element name="Map" type="o:Map" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

  <complexType name="Map">
    <sequence>
      <element name="Source" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Destination" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Aspect">
    <sequence>
      <element name="Tag" type="string" maxOccurs="1" minOccurs="1"></element>
      <element name="Keyword" type="string" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Search" type="string" maxOccurs="unbounded" minOccurs="1"></element>
      <element name="Resolve" type="o:Resolve" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="Result" type="o:Result" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>

    <complexType name="Resolve">
    <simpleContent>
      <extension base="string">
        <attribute name="filter" type="string"/>
        <attribute name="type" type="string" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="NewType">
    <restriction base="token">
      <enumeration value="or"></enumeration>
      <enumeration value="and"></enumeration>
    </restriction>
  </simpleType>


  <complexType name="Parameters">
    <sequence>
      <element name="Parameter" type="o:Parameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="CommandParameter">
    <sequence>
      <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>


  <complexType name="MethodParameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"></element>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"></element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"></element>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"></element>
    </all>
  </complexType>

  <complexType name="MethodParameters">
    <sequence>
      <element name="MethodParameter" type="o:MethodParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="BackendParameter">
    <simpleContent>
      <extension base="string">
        <anyAttribute processContents="lax" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="BackendParameters">
    <sequence>
      <element name="Backend" type="o:BackendParameter" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="References">
    <sequence>
      <element name="Reference" type="o:Reference" maxOccurs="unbounded" minOccurs="1"></element>
    </sequence>
  </complexType>

  <complexType name="Reference">
    <sequence>
      <element name="Object" type="token"></element>
      <element name="Attribute" type="token"></element>
    </sequence>
  </complexType>
</schema>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/sambadomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>SambaDomain</Name>
		<Description>Samba domain</Description>
		<DisplayName>Samba domain</DisplayName>
		<BackendParameters>
			<Backend objectClasses="sambaDomain" RDN="sambaDomainName">LDAP</Backend>
		</BackendParameters>
    <Backend>LDAP</Backend>
    <Attributes>
      <Attribute>
        <Name>sambaDomainName</Name>
        <Description>Windows NT domain</Description>
        <Type>UnicodeString</Type>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>sambaSID</Name>
        <Description>Security ID</Description>
        <Type>UnicodeString</Type>
        <Mandatory>true</Mandatory>
      </Attribute>
      <Attribute>
        <Name>sambaAlgorithmicRidBase</Name>
        <Description>Base at which the samba RID generation algorithm should operate</Description>
        <Type>Integer</Type>
        <Default>1000</Default>
      </Attribute>
      <Attribute>
        <Name>sambaNextUserRid</Name>
        <Description>Next NT rid to give our for users</Description>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaMinPwdLength</Name>
        <Description>Minimal password length (default: 5)</Description>
        <Default>5</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaPwdHistoryLength</Name>
        <Description>Length of Password History Entries (default: 0 => off)</Description>
        <Default>0</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaLogonToChgPwd</Name>
        <Description>Force Users to logon for password change (default: 0 => off, 2 => on)</Description>
        <Default>0</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaMaxPwdAge</Name>
        <Description>Maximum password age, in seconds (default: -1 => never expire passwords)</Description>
        <Default>-1</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaMinPwdAge</Name>
        <Description>Minimum password age, in seconds (default: 0 => allow immediate password change)</Description>
        <Default>0</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaLockoutDuration</Name>
        <Description>Lockout duration in minutes (default: 30, -1 => forever)</Description>
        <Default>30</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaLockoutObservationWindow</Name>
        <Description>Reset time after lockout in minutes (default: 30)</Description>
        <Default>30</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaLockoutThreshold</Name>
        <Description>Lockout users after bad logon attempts (default: 0 => off)</Description>
        <Default>0</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaForceLogoff</Name>
        <Description>Disconnect Users outside logon hours (default: -1 => off, 0 => on)</Description>
        <Default>-1</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaRefuseMachinePwdChange</Name>
        <Description>Allow Machine Password changes (default: 0 => off)</Description>
        <Default>0</Default>
        <Type>Integer</Type>
      </Attribute>
      <Attribute>
        <Name>sambaNextRid</Name>
        <Description>Next NT rid to give out for anything</Description>
        <Type>Integer</Type>
      </Attribute>
    </Attributes>
    <BaseObject>true</BaseObject>
    <Find>
      <Aspect>
        <Tag>SambaDomain</Tag>
        <Keyword>Samba</Keyword>
        <Keyword>Domain</Keyword>
        <Search>sambaDomainName</Search>
        <Result>
          <Map>
            <Source>sambaDomainName</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>
  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/installed-device.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>InstalledDevice</Name>
		<Description>Object class for bundling installation recipes</Description>
		<DisplayName>InstalledDevice</DisplayName>
		<BackendParameters>
			<Backend objectClasses="installRecipe">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>
		<Attributes>
			<Attribute>
				<Name>installTemplateDN</Name>
				<Description></Description>
				<Type>String</Type>
				<Validators>
					<Condition>
						<Name>IsExistingDN</Name>
					</Condition>
				</Validators>
			</Attribute>
			<Attribute>
				<Name>installNTPServer</Name>
				<Description></Description>
        <Type>String</Type>
        <Validators>
          <Condition>
            <Name>IsValidHostName</Name>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>installRootEnabled</Name>
        <Description></Description>
        <Type>Boolean</Type>
      </Attribute>
      <Attribute>
        <Name>installRootPasswordHash</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
      </Attribute>
      <Attribute>
        <Name>installKeyboardlayout</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installSystemLocale</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installTimezone</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installMirrorDN</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installTimeUTC</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installMirrorPoolDN</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <!--
      <Attribute>
        <Name>installPartitionTable</Name>
        <Description></Description>
        <Type>DevicePartitionTableType</Type>
        <BackendType>UnicodeString</BackendType>
      </Attribute>
      -->
      <Attribute>
        <Name>installRecipeDN</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
      <Attribute>
        <Name>installRelease</Name>
        <Description></Description>
        <Type>String</Type>
      </Attribute>
    </Attributes>
    <Extends>
      <Value>Device</Value>
    </Extends>
    <BaseObject>false</BaseObject>
  </Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/samba-ws-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>SambaWorkstationContainer</Name>
		<DisplayName>Samba Workstation Container</DisplayName>
		<Description>Organizational unit that can contain Samba workstations</Description>
		<BackendParameters>
			<Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>

		<BaseObject>true</BaseObject>
		<FixedRDN>ou=winstations</FixedRDN>
                <StructuralInvisible>true</StructuralInvisible>
		<Container>
			<Type>SambaMachineAccount</Type>
		</Container>
	</Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/phone-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>PhoneContainer</Name>
		<DisplayName>Phones</DisplayName>
		<Description>Organizational unit that can contain phones</Description>
		<BackendParameters>
			<Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>
		<Container>
			<Type>goFonHardware</Type>
		</Container>
		<BaseObject>true</BaseObject>
		<FixedRDN>ou=phones</FixedRDN>
	</Object>
</Objects>

=== gonicus/clacks/agent/src/clacks/agent/data/objects/user-shadow.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>ShadowUser</Name>
    <DisplayName>Shadow extension</DisplayName>
    <Templates>
      <Template>user-shadow.ui</Template>
    </Templates>
    <Description>A Shadow extension for a generic user</Description>
    <BaseObject>false</BaseObject>
    <BackendParameters>
      <Backend objectClasses="shadowAccount">LDAP</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>

    <Attributes>
      <Attribute>
        <Name>shadowLastChange</Name>
        <Description>The dat of the last password change.</Description>
        <Type>Timestamp</Type>
        <BackendType>Integer</BackendType>
	<ReadOnly>true</ReadOnly>
        <InFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>ShadowDaysToDatetime</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </InFilter>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>DatetimeToShadowDays</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
      </Attribute>

      <Attribute>
        <Name>shadowMin</Name>
        <Description>The minimum password age is the number of days the user will have to wait before she will be allowed to change her password again.</Description>
        <Type>Integer</Type>
      </Attribute>

      <Attribute>
        <Name>shadowMax</Name>
        <Description>The maximum password age is the number of days after which the user will have to change her password.</Description>
        <Type>Integer</Type>
      </Attribute>

      <Attribute>
        <Name>shadowWarning</Name>
        <Description>The number of days before a password is going to expire (see the shadowMax) during which the user should be warned.</Description>
        <Type>Integer</Type>
      </Attribute>

      <Attribute>
        <Name>shadowInactive</Name>
        <Description>The number of days after a password has expired (see the shadowMax) during which the password should still be accepted (and the user should update her password during the next login).</Description>
        <Type>Integer</Type>
      </Attribute>

      <Attribute>
        <Name>shadowExpire</Name>
        <Description>The date of expiration of the account.</Description>
        <Type>Timestamp</Type>
        <BackendType>Integer</BackendType>
        <InFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>ShadowDaysToDatetime</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </InFilter>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>DatetimeToShadowDays</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
      </Attribute>

      <Attribute>
        <Name>shadowFlag</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
      </Attribute>
    </Attributes>

    <Extends>
      <Value>User</Value>
    </Extends>

    <RequiresExtension>
      <Extension>PosixUser</Extension>
    </RequiresExtension>

  </Object>
</Objects>
